package P2PClient.Peer2Peer;

/**
* Peer2Peer/P2PHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P2P.idl
* Monday, April 11, 2016 1:43:49 AM ADT
*/

public final class P2PHolder implements org.omg.CORBA.portable.Streamable
{
  public P2PClient.Peer2Peer.P2P value = null;

  public P2PHolder ()
  {
  }

  public P2PHolder (P2PClient.Peer2Peer.P2P initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = P2PClient.Peer2Peer.P2PHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
	  P2PClient.Peer2Peer.P2PHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return P2PClient.Peer2Peer.P2PHelper.type ();
  }

}
