package P2PClient.Peer2Peer;


/**
* Peer2Peer/P2POperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P2P.idl
* Monday, April 11, 2016 1:43:49 AM ADT
*/

public interface P2POperations 
{
  boolean registerIP (String name, String ip);
  boolean registerFile (String fileName, String fileLocation, String user);
  boolean removeFile (String fileName, String userID);
  String requestFile (String fileName);
  String requestFileList ();
  void deleteUser (String userName);
  String sendFile (String fileName);
  String filePath (String serverName, String fileName);
  void shutdown ();
} // interface P2POperations
