package Peer2Peer;


/**
* Peer2Peer/P2P.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from P2P.idl
* Monday, April 11, 2016 1:26:09 AM ADT
*/

public interface P2P extends P2POperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface P2P
